name: Run Tests and CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop, feature/* ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggers

jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y default-libmysqlclient-dev build-essential pkg-config
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
        pip install pytest pytest-cov pytest-flask pytest-mock flask-sqlalchemy mysqlclient
    
    - name: Run linting and code quality checks
      run: |
        echo "Running code quality checks..."
        # Check for syntax errors
        python -m py_compile app.py || true
        # Check imports
        python -c "import app" || true
        
        # Count test files
        echo "Test files found:"
        find . -name "test_*.py" -type f | wc -l
        find . -name "test_*.py" -type f
    
    - name: Run unit tests
      env:
        DATABASE_URL: mysql://root:root@localhost:3306/test_db
        FLASK_ENV: testing
        SECRET_KEY: test-secret-key-for-github-actions
      run: |
        echo "Running unit tests..."
        pytest test_user_model.py \
               test_enrollment_model.py \
               test_course_model.py \
               test_assignment_model.py \
               test_submission_model.py \
               test_announcement_model.py \
               test_instructor_model.py \
               test_student_model.py \
               test_ta_model.py \
               -v --tb=short
    
    - name: Run controller tests
      env:
        DATABASE_URL: mysql://root:root@localhost:3306/test_db
        FLASK_ENV: testing
        SECRET_KEY: test-secret-key-for-github-actions
      run: |
        echo "Running controller tests..."
        pytest test_auth_controller.py \
               test_admin_controller.py \
               test_instructor_controller.py \
               test_student_controller.py \
               test_ta_controller.py \
               -v --tb=short
    
    - name: Run integration tests
      env:
        DATABASE_URL: mysql://root:root@localhost:3306/test_db
        FLASK_ENV: testing
        SECRET_KEY: test-secret-key-for-github-actions
      run: |
        echo "Running integration tests..."
        pytest test_integration.py -v --tb=short
    
    - name: Run security tests
      env:
        DATABASE_URL: mysql://root:root@localhost:3306/test_db
        FLASK_ENV: testing
        SECRET_KEY: test-secret-key-for-github-actions
      run: |
        echo "Running security tests..."
        pytest test_security.py -v --tb=short
    
    - name: Run performance tests
      env:
        DATABASE_URL: mysql://root:root@localhost:3306/test_db
        FLASK_ENV: testing
        SECRET_KEY: test-secret-key-for-github-actions
      run: |
        echo "Running performance tests..."
        pytest test_performance.py -v --tb=short
    
    - name: Run test coverage
      env:
        DATABASE_URL: mysql://root:root@localhost:3306/test_db
        FLASK_ENV: testing
        SECRET_KEY: test-secret-key-for-github-actions
      run: |
        echo "Running test coverage analysis..."
        pytest --cov=./ --cov-report=xml --cov-report=html --cov-report=term-missing \
               test_*.py -v
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          htmlcov/
          coverage.xml
          .coverage
        retention-days: 7
    
    - name: Generate test report
      if: always()
      run: |
        echo "# Test Results Summary" > test-report.md
        echo "Generated: $(date)" >> test-report.md
        echo "" >> test-report.md
        echo "## Python Version: ${{ matrix.python-version }}" >> test-report.md
        echo "" >> test-report.md
        echo "### Test Categories:" >> test-report.md
        echo "- ✅ Model Tests: 8 files" >> test-report.md
        echo "- ✅ Controller Tests: 5 files" >> test-report.md
        echo "- ✅ Integration Tests: 1 file" >> test-report.md
        echo "- ✅ Security Tests: 1 file" >> test-report.md
        echo "- ✅ Performance Tests: 1 file" >> test-report.md
        echo "" >> test-report.md
        echo "### Coverage:" >> test-report.md
        echo "Coverage reports available in artifacts" >> test-report.md
    
    - name: Upload test report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-report-${{ matrix.python-version }}
        path: test-report.md

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/course-management-system:latest
          ${{ secrets.DOCKER_USERNAME }}/course-management-system:${{ github.sha }}

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: [test, build-docker]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up deployment
      run: |
        echo "Deployment would happen here"
        echo "For production, this would deploy to:"
        echo "- Heroku"
        echo "- AWS Elastic Beanstalk"
        echo "- Google Cloud Run"
        echo "- Or any other cloud provider"
        
        # Create deployment summary
        echo "## Deployment Summary" > deployment-summary.md
        echo "Application: Course Management System" >> deployment-summary.md
        echo "Commit: ${{ github.sha }}" >> deployment-summary.md
        echo "Branch: ${{ github.ref }}" >> deployment-summary.md
        echo "Timestamp: $(date)" >> deployment-summary.md
        echo "" >> deployment-summary.md
        echo "### Test Results:" >> deployment-summary.md
        echo "All tests passed successfully" >> deployment-summary.md
        echo "" >> deployment-summary.md
        echo "### Docker Image:" >> deployment-summary.md
        echo "Built and pushed to Docker Hub" >> deployment-summary.md
    
    - name: Upload deployment summary
      uses: actions/upload-artifact@v3
      with:
        name: deployment-summary
        path: deployment-summary.md

  notifications:
    name: Send Notifications
    runs-on: ubuntu-latest
    needs: [test, build-docker, deploy]
    if: always()
    
    steps:
    - name: Send Slack notification
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: GitHub Actions
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    - name: Create GitHub Deployment Status
      uses: bobheadxi/deployments@v1
      if: always()
      with:
        step: finish
        token: ${{ github.token }}
        env: Production
        status: ${{ job.status }}
        deployment_id: ${{ github.run_id }}
    
    - name: Summary
      run: |
        echo "CI/CD Pipeline Completed"
        echo "========================"
        echo "Tests: ${{ needs.test.result }}"
        echo "Docker Build: ${{ needs.build-docker.result }}"
        echo "Deployment: ${{ needs.deploy.result }}"
        echo ""
        echo "View test results in artifacts"